### ISSUE TITLE
Chart handles missing data inconsistently

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-server-node#14]
The chart API grouping differs by field type.
- for boolean fields it treats undefined as false (returning 'No')
- for LOV fields any invalid value will be dropped by the JOIN (*)
- for others I assume they will go in an SQL NULL group (*)
Note (*) not seen in the sample data.

My preference would be to group them in an 'Unknown' category, but at least they should be consistent.

**Comment by evoluteur** [comment]
It may not be consistent in the way a DBA would look at it but it is consistent with the UI because that is what users will expect.
For boolean fields nulls are the same as false b/c checkboxes treat them the same.
LOV fields use a left join so null and invalid keys fall into the same N/A bucket as dropdowns will show empty.
The "Unknown" group is called "N/A".

**Comment by evoluteur** [comment]
On second thought, if the user is a data scientist or DBA he may want the charts to differentiate b/w null and false for boolean...
Ideally there should be new options in the config for charts.

**Comment by david-pfx** [comment]
Yes, I think that would be preferable. But consistency in treatment was my main concern.

 

Regards

David M Bennett FACS

  _____  

Puzzlang – Pattern language and Unity player for abstract single-player games and puzzles  -- http://www.polyomino.com <http://www.polyomino.com/>
